name: Windows CI

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ghc: ["8.8.4"]

    steps:
      - name: Set up GHC
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Update cabal
        run: cabal update

      - name: Build project
        run: |
          .\win_setup.bat
          cabal build

      - name: Create a zip with exe file and assets
        run: |
          mkdir -p Game
          cp $(cabal list-bin Game) Game/
          cp -r assets Game/
          cp sdl2_local_win/bin/SDL2.dll Game/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: Game
